package ventanas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import clases.Coneccion;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author luciano
 */
public class InformacionEquipo extends javax.swing.JFrame {

    /**
     * Creates new form InformacionEquipo
     */
    int idEquipo, idClienteUpdate ;
    String user,diaI, mesI, annioI, comTec,
            reviTec, fechaIngreso;

    public InformacionEquipo() {
        idEquipo = InformacionCliente.idEquipo;
        idClienteUpdate = GestionarClientes.idClienteUpdate;
        user = Login.userName;
        initComponents();
        setResizable(false);
        setSize(670, 530);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(labelFondo.getWidth(), labelFondo.getHeight(), Image.SCALE_DEFAULT));
        labelFondo.setIcon(icono);
        this.repaint();

        setTitle("Información del equipo");

        try {
            Coneccion cn1 = new Coneccion();
            Connection con1 = cn1.conectar();

            PreparedStatement pst1 = con1.prepareStatement("select nombre_cliente from clientes where id_cliente = '" + idClienteUpdate + "'");
            ResultSet rs1 = pst1.executeQuery();

            if (rs1.next()) {
                setTitle("Información del equipo de " + rs1.getString("nombre_cliente"));
                txtNombreCliente.setText(rs1.getString("nombre_cliente"));
            }
            cn1.desconectar();
        } catch (SQLException e) {
            System.err.println("Error al obtener nombre del cliente. " + e);
        }

        try {
            Coneccion cn = new Coneccion();
            Connection con = cn.conectar();
            String Query = "select tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso,annio_ingreso,"
                    + "observaciones,estatus,ultima_modificacion,comentarios_tecnico,revision_tecnica_de from equipos where id_equipo = '" + idEquipo + "'";
            PreparedStatement pst = con.prepareStatement(Query);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                comboTipoEquipo.setSelectedItem(rs.getString(1));
                comboMarcaEquipo.setSelectedItem(rs.getString(2));
                txtModelo.setText(rs.getString(3));
                txtNumSerie.setText(rs.getString(4));
                diaI = rs.getString(5);
                mesI = rs.getString(6);
                annioI = rs.getString(7);

                fechaIngreso = diaI + "/" + mesI + "/" + annioI;

                txtPaneObservaciones.setText(rs.getString(8));
                comboEstado.setSelectedItem(rs.getString(9));
                txtUltimaModificacion.setText(rs.getString(10));
                comTec = rs.getString(11);
                reviTec = rs.getString(12);

                txtFecha.setText(fechaIngreso);
                if(reviTec == null){
                    labelNombreTecnico.setText("Comentarios y actualización del técnico: ");
                }else{
                    labelNombreTecnico.setText("Comentarios y actualización del técnico: " + reviTec);
                }
                
                txtPaneComentarioTecnico.setText(comTec);
            }
        } catch (SQLException e) {
            System.err.println("Error " + e);
        } 

    }

    //Cambiando el icono del JFrameLogin anteriormente editado en
    //propiedades/iconImage/value from existing component/propety/iconImage/ OK
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laberTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        labelNombre3 = new javax.swing.JLabel();
        labelNombre4 = new javax.swing.JLabel();
        labelNombre5 = new javax.swing.JLabel();
        labelNombre6 = new javax.swing.JLabel();
        labelNombre7 = new javax.swing.JLabel();
        labelNombre8 = new javax.swing.JLabel();
        labelNombreTecnico = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtUltimaModificacion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        comboTipoEquipo = new javax.swing.JComboBox<>();
        comboMarcaEquipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneObservaciones = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPaneComentarioTecnico = new javax.swing.JTextPane();
        botonActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        laberTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        laberTitulo.setForeground(new java.awt.Color(255, 255, 255));
        laberTitulo.setText("Información del Equipo");

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre del cliente:");

        labelNombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre1.setText("Tipo de equipo:");

        labelNombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre2.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre2.setText("Marca:");

        labelNombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre3.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre3.setText("Modelo:");

        labelNombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre4.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre4.setText("Número de serie:");

        labelNombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre5.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre5.setText("Fecha de ingreso:");

        labelNombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre6.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre6.setText("Última modificación por:");

        labelNombre7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre7.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre7.setText("Estado:");

        labelNombre8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre8.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre8.setText("Daño reportado y observaciones:");

        labelNombreTecnico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombreTecnico.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreTecnico.setText("Comentarios y actualización del técnico:");

        txtNombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        txtNombreCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreCliente.setEnabled(false);
        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyTyped(evt);
            }
        });

        txtModelo.setBackground(new java.awt.Color(153, 153, 255));
        txtModelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));
        txtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModeloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });

        txtNumSerie.setBackground(new java.awt.Color(153, 153, 255));
        txtNumSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNumSerie.setForeground(new java.awt.Color(255, 255, 255));
        txtNumSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumSerieKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumSerieKeyTyped(evt);
            }
        });

        txtUltimaModificacion.setBackground(new java.awt.Color(153, 153, 255));
        txtUltimaModificacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtUltimaModificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtUltimaModificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUltimaModificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUltimaModificacion.setEnabled(false);
        txtUltimaModificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUltimaModificacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUltimaModificacionKeyTyped(evt);
            }
        });

        txtFecha.setBackground(new java.awt.Color(153, 153, 255));
        txtFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFecha.setEnabled(false);
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ingreso", "No reparado", "En revisión", "Reparado", "Entregado" }));

        comboTipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));

        comboMarcaEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alienware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Philips" }));

        jScrollPane1.setViewportView(txtPaneObservaciones);

        txtPaneComentarioTecnico.setEditable(false);
        jScrollPane2.setViewportView(txtPaneComentarioTecnico);

        botonActualizar.setBackground(new java.awt.Color(153, 153, 255));
        botonActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizar.setText("Actualizar");
        botonActualizar.setBorder(null);
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Creado por Luciano Salgado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelNombre3))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(labelNombre8))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(labelNombreTecnico))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtUltimaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(comboTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelNombre6))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(labelNombre7))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelNombre))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelNombre4))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelNombre1))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(laberTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelNombre2))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(comboMarcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(labelNombre5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(labelNombre3))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(labelNombre8))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(labelNombreTecnico))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(txtUltimaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(comboTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(labelNombre6))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(labelNombre7))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(labelNombre))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(labelNombre4))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(labelNombre1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(laberTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(labelNombre2))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(comboMarcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(labelNombre5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyReleased

    }//GEN-LAST:event_txtNombreClienteKeyReleased

    private void txtNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyTyped
        Color col = new Color(153, 153, 255);
        txtNombreCliente.setBackground(col);

        if (txtNombreCliente.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreClienteKeyTyped

    private void txtModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyReleased

    }//GEN-LAST:event_txtModeloKeyReleased

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
        Color col = new Color(153, 153, 255);
        txtModelo.setBackground(col);

        if (txtModelo.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtNumSerieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSerieKeyReleased

    }//GEN-LAST:event_txtNumSerieKeyReleased

    private void txtNumSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSerieKeyTyped
        Color col = new Color(153, 153, 255);
        txtNumSerie.setBackground(col);

        if (txtNumSerie.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumSerieKeyTyped

    private void txtUltimaModificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUltimaModificacionKeyReleased

    }//GEN-LAST:event_txtUltimaModificacionKeyReleased

    private void txtUltimaModificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUltimaModificacionKeyTyped
        Color col = new Color(153, 153, 255);
        txtNombreCliente.setBackground(col);

        if (txtNombreCliente.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUltimaModificacionKeyTyped

    private void txtFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyReleased

    }//GEN-LAST:event_txtFechaKeyReleased

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped

    }//GEN-LAST:event_txtFechaKeyTyped

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        int var = 0;
        String modelo = txtModelo.getText().trim();
        String num_serie = txtNumSerie.getText().trim();
        String tipo_equipo = comboTipoEquipo.getSelectedItem().toString();
        String marca = comboMarcaEquipo.getSelectedItem().toString();
        String observaciones = txtPaneObservaciones.getText();
        String estatus = comboEstado.getSelectedItem().toString();
        String ultima_modificacion = user;

        if (modelo.equals("")) {
            txtModelo.setBackground(Color.red);
            var++;
        }
        if (num_serie.equals("")) {
            txtNumSerie.setBackground(Color.red);
            var++;
        }
        if (txtPaneObservaciones.equals("")) {
            txtPaneObservaciones.setText("Sin Observaciones.");
            var++;
        }

        if (var == 0) {
            try {
                Coneccion cn = new Coneccion();
                Connection con = cn.conectar();
                String Query = "update equipos set tipo_equipo=?, marca=?, modelo=?, num_serie=?,observaciones=?,"
                        + "estatus=?,ultima_modificacion=? where id_equipo = '" + idEquipo + "'";
                PreparedStatement pst = con.prepareStatement(Query);

                pst.setString(1,tipo_equipo);
                pst.setString(2,marca);
                pst.setString(3,modelo);
                pst.setString(4,num_serie);
                pst.setString(5,observaciones);
                pst.setString(6,estatus);
                pst.setString(7,ultima_modificacion);
                
                pst.executeUpdate();
                
                txtFecha.setBackground(Color.GREEN);
                txtModelo.setBackground(Color.GREEN);
                txtNombreCliente.setBackground(Color.GREEN);
                txtNumSerie.setBackground(Color.GREEN);
                txtUltimaModificacion.setBackground(Color.GREEN);
                
                  txtUltimaModificacion.setText(user);
                System.out.println("Un equipo a sido actualizado.");
                JOptionPane.showMessageDialog(null, "Equipo Actualizado.");
                con.close();
            } catch (SQLException e) {
                System.err.println("Error al actualizar equipo." + e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No pueden quedar campos en blanco");
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboMarcaEquipo;
    private javax.swing.JComboBox<String> comboTipoEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JLabel labelNombre4;
    private javax.swing.JLabel labelNombre5;
    private javax.swing.JLabel labelNombre6;
    private javax.swing.JLabel labelNombre7;
    private javax.swing.JLabel labelNombre8;
    private javax.swing.JLabel labelNombreTecnico;
    private javax.swing.JLabel laberTitulo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextPane txtPaneComentarioTecnico;
    private javax.swing.JTextPane txtPaneObservaciones;
    private javax.swing.JTextField txtUltimaModificacion;
    // End of variables declaration//GEN-END:variables

}
